services:
  bitcoin:
    container_name: bitcoin
    image: dobtc/bitcoin:latest
    ports:
      - 8332:8332
      - 8333:8333
    volumes:
      - /opt/bitcoin:/home/bitcoin/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
