name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'      
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Docker build
        id: prepare
        run: |
          TARGET_RC=$(grep --only-matching --perl-regex "(?<=BITCOIN_RC\=).*" ./Dockerfile)
          TARGET_VERSION=$(grep --only-matching --perl-regex "(?<=BITCOIN_VERSION\=).*" ./Dockerfile)
          [ -n "$TARGET_RC" ] && TARGET_VERSION=$TARGET_VERSION$TARGET_RC
          PUSH=true
          TAGS=()
          TAGS=("${{ github.repository }}:${TARGET_VERSION/\//-}")
          [ -z "$TARGET_RC" ] && TAGS+=("${{ github.repository }}:latest")
          TAGS+=("ghcr.io/${{ github.repository }}:${TARGET_VERSION/\//-}")
          [ -z "$TARGET_RC" ] && TAGS+=("ghcr.io/${{ github.repository }}:latest")
          PLATFORMS="linux/amd64,linux/arm/v7,linux/arm64"

          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=docker_platforms::${PLATFORMS}
          echo ::set-output name=push::${PUSH}
          echo ::set-output name=tags::${TAGS[@]}
          echo ::set-output name=version::${TARGET_VERSION}
          echo ::set-output name=build::true

      - if: ${{ steps.prepare.outputs.build }} == 'true'
        name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - if: ${{ steps.prepare.outputs.build }} == 'true'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - if: ${{ steps.prepare.outputs.build }} == 'true'
        name: Build Docker image
        run: |
          TAGS=(${{ steps.prepare.outputs.tags }})

          echo "Build date: ${{ steps.prepare.outputs.build_date }}"
          echo "Docker platform: ${{ steps.prepare.outputs.docker_platforms }}"
          echo "Push: ${{ steps.prepare.outputs.push }}"
          echo "Tags: ${{ steps.prepare.outputs.tags }}"

          echo docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=${{steps.prepare.outputs.push}}" \
            --progress=plain \
            --build-arg "BUILD_RUN=${GITHUB_RUN_ID}" \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .

          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=${{steps.prepare.outputs.push}}" \
            --progress=plain \
            --build-arg "BUILD_RUN=${GITHUB_RUN_ID}" \
            --build-arg "BUILD_DATE=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
            
      - if:  ${{ steps.prepare.outputs.build }} == 'true'
        name: Clear Docker credentials
        run: |
          rm -f ${HOME}/.docker/config.json
          
      - name: Create a release
        uses: action-pack/github-release@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "${{ steps.prepare.outputs.version }}"
          title: "${{ steps.prepare.outputs.version }}"
          body: "Release ${{ steps.prepare.outputs.version }}"
